### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by apex1310** [Collusion/pickmybrain#1]
sorry but your installer doesn't work on PHP 5.3 and PHP 8.3, same errors

Warning: Undefined variable $e in control.php on line 402

Fatal error: Uncaught Error: Call to a member function getMessage() on null in control.php:402 
Stack trace: #0 {main} thrown in control.php on line 402

**Comment by Collusion** [comment]
Due to a logic flaw in the code in control.php checkPMBIndexes() function call failure resulted in an uncaught error.

This is now fixed and you should see a more accurate error message instead.

Please update control.php, tokenizer_functions.php & bin32/tokenizer_functions.php files with the newer versions.

**Comment by apex1310** [comment]
yup, now i have error
Error: table PMBIndexes could not be created or modified.
Error: unable to check existing indexes
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pickmybrain.pmbindexes' doesn't exist

**Comment by Collusion** [comment]
Which database (name + version) are you using?

Also I would need to see your database configuration in db_connection.php - please omit all passwords before submitting. 

You can also send it via an email to henri.ruutinen@pickmybra.in

**Comment by apex1310** [comment]
Server type: MySQL
Server version: 8.2.0 - MySQL Community Server - GPL

yup, it's database issue, on newer mysql versions install script is throwing errors on "disabled_documents" and "type" fields during manual pmbindexes table creation.

Query error:
#1101 - BLOB, TEXT, GEOMETRY or JSON column 'disabled_documents' can't have a default value

**Comment by Collusion** [comment]
Can you check if MySQL strict mode is enabled? This can be done by running:

SHOW VARIABLES LIKE 'sql_mode';

**Comment by apex1310** [comment]
STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

**Comment by apex1310** [comment]
with disabled strict mode i get error
#1067 - Invalid default value for 'type'

**Comment by Collusion** [comment]
Strict mode seems to be enabled, pickmybrain doesn't currently play well with this setting.

I did update the failing checkPMBIndexes() function in question to be more compliant with MySQL strict mode, but there might be other SQL queries which are still non-compliant. Please update tokenizer_functions.php & bin32/tokenizer_functions.php files with the updated versions.

Strict mode can be disabled by running:
set global sql_mode='';

To enable it later again you can run:
set global sql_mode='STRICT_TRANS_TABLES';

**Comment by apex1310** [comment]
ok, on php 8.3 there are many depraced functions but on 5.3 works, there are errors like
Notice: Undefined offset: 3 in decode_asc.php on line 165 showing up in search field

i have tryed to index some database, great that there is a option for that. awesome man, fast, crazy logic around indexing

**Comment by Collusion** [comment]
I can look into making pickmybrain fully PHP 8 compatible, shouldn't be too hard. 

About this error:
Notice: Undefined offset: 3 in decode_asc.php on line 165 showing up in search field

I can try and replicate it, but meanwhile, can you try reindexing? Does that help?

**Comment by apex1310** [comment]
reindexing doesn't help
![Screenshot 2024-12-27 1633485665](https://github.com/user-attachments/assets/fb67ad40-3831-424a-ab85-f072217bbaeb)

also i have noticed when i delete entry from my table and do reindex, index still shows same amount of scaned documents and i can find that entry if i look in both pmbtokens and pmbtoktemp table.  So table is not refreshed correctly, that entry should be deleted.

**Comment by Collusion** [comment]
The undefined offsets in the picture above; are they document ids that you have since removed from your dataset?

If you run the indexer again without explicit purge or replace command, the old data will not actually be re-indexed/re-investigated again. Instead, the indexer just gets documents ids that have larger value than the previous maximum document id and either:

1. Merges the new documents into the existing search index (slower indexing, marginally better searching performance) 
2. Places them into a delta index (faster indexing, marginally slower searching performance).

This is determined by the index grow method found in the web control panel. 

And the third option is of course to re-index everything again with purge/replace parameter - this may be the preferred method, if your dataset is undergoes regular updates. 

If you just need to exclude removed/deprecated documents from the search index, you can do this without re-indexing by calling the following method included in the PMBApi: 

$pickmybrain = new PMBApi();

/* array of deprecated/non-existing document ids  */
$array_of_deprecated_ids = array(10, 12, 15); 

/* disable given document ids */
$pickmybrain->DisableDocuments("my_index_name", $array_of_deprecated_ids);

**Comment by apex1310** [comment]
to answer top question, no they are not ids of removed documents, i get that with fresh purged and reindexed database.

**Comment by apex1310** [comment]
now from my point of view reindexing shold work in that way that if some document is removed from original database so why keeping them into pmb database, just remove them also. In this way if you don't use mentioned method of exluding ids, there are entries in search that point to not existing ids. Manualy tracking of removed id's is complicated if you have many documents, not to mention if more people are using database which is in 99% of cases, how to track which docment is removed. I don't know maybe simple scan original table for removed id's and if they exists remove them from pmb database also. that shouldn't take too much time to process because you are not indexing whole database again. Or maybe im wrong and whole index is needed to be created again?

**Comment by Collusion** [comment]
> to answer top question, no they are not ids of removed documents, i get that with fresh purged and reindexed database.

Okay, I need to look at this more closely. I'm going to open another issue. I'm going to tag you there as well. 

> now from my point of view reindexing shold work in that way that if some document is removed from original database so why keeping them into pmb database, just remove them also. In this way if you don't use mentioned method of exluding ids, there are entries in search that point to not existing ids. Manualy tracking of removed id's is complicated if you have many documents, not to mention if more people are using database which is in 99% of cases, how to track which docment is removed. I don't know maybe simple scan original table for removed id's and if they exists remove them from pmb database also. that shouldn't take too much time to process because you are not indexing whole database again. Or maybe im wrong and whole index is needed to be created again?

I guess there could be a command for automatically disabling all deprecated documents in the search index, if you are not willing or able to disable them individually. This would require a comparison between PMBDocinfo and the original data table, which in turn would require some resources&time for a big index. 

I think I am going to close this issue for now, since we are pretty far from the original scope already.
